FROM     ubuntu:14.04
MAINTAINER Shaozhen Ding "dsz0111@gmail.com"

# make sure the package repository is up to date
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y openjdk-7-jdk
RUN apt-get -y install gradle
# RUN apt-get install -y openssl libreadline6 libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion pkg-config
